[build-system]
requires = ["setuptools>=65.0.2","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytorch-onn"
version = "0.1.0"
description = "A PyTorch Library for Photonic Integrated Circuit Simulation and Photonic AI Computing"
authors = [
  { name = "JeremieMelo et al.", email = "" }
]
readme = "README.md"
requires-python = ">=3.7,<=3.13"
license = { file = "LICENSE" }
keywords = ["photonic","ONN","pytorch","optics"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "License :: OSI Approved :: MIT License"
]

[project.dependencies]
torch = ">=2.0.0"
tensorflow = ">=2.12.0"
pyutils = ">=0.0.2"
numpy = ">=1.24.0"