# Configuración por defecto para TorchONN
system:
  device: "auto"  # auto, cpu, cuda, mps
  dtype: "float32"
  wavelength: 1.55e-6  # metros
  
simulation:
  precision: "single"  # single, double
  backend: "torch"
  
training:
  batch_size: 32
  learning_rate: 1e-3
  num_epochs: 100
  optimizer: "adam"
  
logging:
  level: "INFO"
  save_logs: true
  log_dir: "logs"
